---
- name: Master Playbook for Ansible
  hosts: zoslab
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    ZOAU: /usr/lpp/IBM/zoautil
    PYZ: /usr/lpp/IBM/cyp/v3r11/pyz
  tasks:
    - name: Bootstrap message
      ansible.builtin.debug:
        msg: "Starting master playbook --"

    - name: Load RACF variables dynamically
      ansible.builtin.include_vars:
        file: racf_vars.yml

    - name: Create Team, Users, and Verify
      ansible.builtin.include_tasks: create_team01_and_users_verify.yml

    - name: Create Dev and Test Libraries
      ansible.builtin.include_tasks: create_dev_test_libraries.yml

    - name: Run Master Playbook for Roles
      ansible.builtin.include_tasks: roles-master-playbook.yml
      vars: 
        seed_base: "/playbooks/seed_files"
        subfolders: 
          - PROCLIB
          - JCL
          - ASM
          - COBOL
          - REXX
